# Generated by Django 5.2.12 on 2026-04-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='userid',
            new_name='user',
        ),
    ]
