# Generated by Django 5.2.12 on 2026-04-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
