# Generated by Django 5.2.12 on 2026-04-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='orderitem',
        ),
    ]
