# Generated by Django 5.2.12 on 2026-04-16 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rating'),
        ('user', '0010_remove_orderitem_order_remove_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=50)),
                ('paymentstatus', models.CharField(default='pending', max_length=50)),
                ('orderstatus', models.CharField(default='pending', max_length=50)),
                ('Carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('trackingid', models.CharField(blank=True, max_length=100, null=True)),
                ('orderdate', models.CharField(max_length=50)),
                ('deliverydate', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.perfume')),
            ],
        ),
    ]
