# Generated by Django 5.2.12 on 2026-03-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfumename', models.CharField(max_length=100)),
                ('perfumebrand', models.CharField(max_length=100)),
                ('perfume_details', models.CharField(max_length=100)),
                ('perfume_price', models.IntegerField()),
                ('perfume_image', models.FileField(upload_to='cover')),
                ('perfume_stock', models.IntegerField()),
                ('perfume_scent', models.CharField(max_length=50)),
                ('perfume_volume', models.CharField(max_length=50)),
                ('perfume_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.category')),
            ],
        ),
    ]
