# Generated by Django 5.2.12 on 2026-03-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='perfume_details',
            field=models.CharField(max_length=500),
        ),
    ]
